service: sls-express # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs8.10
  iamRoleStatements:
  - Action:
      - dynamodb:Query
      - dynamodb:Scan
      - dynamodb:GetItem
      - dynamodb:PutItem
      - dynamodb:UpdateItem
      - dynamodb:DeleteItem
    Resource:
      "Fn::Join":
        - ""
        -
          - "arn:aws:dynamodb:"
          - Ref: "AWS::Region"
          - ":"
          - Ref: "AWS::AccountId"
          - ":table/"
          - Ref: SlsEpresssExampleUsers
    Effect: Allow

functions:
  hello:
    handler: handler.api
    events:
    - http:
        path: /users
        method: get
    - http:
        path: /user
        method: post

resources:
  Resources:
    SlsEpresssExampleUsers:
      Type: 'AWS::DynamoDB::Table'
      Properties: 
        AttributeDefinitions:
          -
            AttributeName: email
            AttributeType: S
        KeySchema:
          -
            AttributeName: email
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: 'SlsEpresssExampleUsers'

plugins:
  - serverless-express
